import {PhysicalQuantities} from "./main.page";

export const QUANTITIES: PhysicalQuantities[] = [
  {name: "Plošný obsah", value: "S", unit: "m²"},
  {name: "Objem", value: "V", unit: "m³"},
  {name: "Rychlost", value: "v", unit: "m/s¹"},
  {name: "Úhlová rychlost", value: "ω", unit: "rad/s¹"},
  {name: "Zrychlení", value: "a", unit: "m/s²"},
  {name: "Tíhové zrychlení", value: "g", unit: "kg/m³"},
  {name: "Hustota", value: "ρ", unit: "kg/m³"},
  {name: "Síla", value: "F", unit: "N"},
  {name: "Tlak", value: "p", unit: "Pa"},
  {name: "Vlnová délka", value: "λ", unit: "m"},
  {name: "Práce", value: "A", unit: "J"},
  {name: "Teplo", value: "Q", unit: "J"},
  {name: "Teplota", value: "t", unit: "°C (K)"},
  {name: "Účinnost", value: "η (éta)", unit: "-(%)"},
  {name: "Výkon", value: "P", unit: "W"},
  {name: "Napětí", value: "U", unit: "V"},
  {name: "El. Proud", value: "I", unit: "A"},
  {name: "El. Potenciál", value: "φ", unit: "V"},
  {name: "El. Odpor", value: "R", unit: "Ω"},
  {name: "Vodivost", value: "G", unit: "S"},
  {name: "Rezistivita", value: "ϱ", unit: "Ω·m"},
  {name: "Hustota proudu", value: "J", unit: "A/m²"},
  {name: "Svítivost", value: "I", unit: "cd"},
  {name: "Intenzita osvětlení", value: "E", unit: "lx"},
  {name: "Intenzita elektrického pole", value: "E", unit: "V/m¹"},
  {name: "Permitivita prostředí", value: "ε", unit: "F/m¹"},
  {name: "Kapacita", value: "C", unit: "F"},
  {name: "Impedance", value: "Z", unit: "Ω"},
  {name: "Reaktance", value: "X", unit: "Ω"},
  {name: "Magnetická indukce", value: "B", unit: "T"},
  {name: "Magnetický indukční tok", value: "Φ", unit: "Wb"},
  {name: "Intenzita magnetického pole", value: "H", unit: "A/m¹"},
  {name: "Permeabilita", value: "μ", unit: "H/m¹"},
  {name: "Indukčnost", value: "L (M)", unit: "H"},
  {name: "Magnetomotorické napětí", value: "Fm", unit: "A"},
  {name: "Magnetický odpor", value: "Rm", unit: "H-¹"},
  {name: "Otáčky el. strojů", value: "n", unit: "min-¹"},
  {name: "Moment síly", value: "M", unit: "Nm"},
  {name: "Konduktivita", value: "γ", unit: "S/m¹"},
  {name: "Magnetická vodivost", value: "λ (Gm)", unit: "H"},
  {name: "Jalový výkon", value: "Q", unit: "var"},
  {name: "Zdánlivý výkon", value: "S", unit: "VA"},
  {name: "Admitance", value: "Y", unit: "S"},
  {name: "Elektrická indukce", value: "D", unit: "C/m²"},
  {name: "Fázový posun", value: "φ", unit: "°"},
  {name: "Účiník ", value: "cosq", unit: "-"},
]
